# commit to be tagged for the new release
commit = "HEAD"

project_name = "Omni"
github_repo = "siderolabs/omni"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

pre_release = false
previous = "v0.43.0"

[notes]

  [notes.reset-machine]
    title = "Reset Removed Machines"
    description = """\
Omni will now try to wipe Talos installation from the machines which are removed from the instance.
"""

  [notes.cluster-resolve]
    title = "Automatically Resolve Cluster in `talosctl`"
    description = """\
`talosctl` command now works without `--cluster` flag when using instance wide Talos config.
Omni will automatically resolve the correct cluster.
"""
