# commit to be tagged for the new release
commit = "HEAD"

project_name = "Omni"
github_repo = "siderolabs/omni"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

pre_release = false
previous = "v0.33.0"

[notes]

  [notes.overlays]
    title = "Talos Overlays Support"
    description = """\
Starting from this version Omni can properly handle Talos overlays during upgrades.
When upgrading SBC nodes from 1.6.x -> 1.7.x Omni will automatically add the correct overlay for the SBC.

Downgrades from 1.7.x to 1.6.x is not recommended.
"""

  [notes.node-audit]
    title = "Kubernetes Node Audit"
    description = """\
Omni now automatically cleans up Kubernetes nodes, which do not have corresponding Omni machines in the cluster.
"""
