# commit to be tagged for the new release
commit = "HEAD"

project_name = "Omni"
github_repo = "siderolabs/omni"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

pre_release = false
previous = "v0.41.0"

[notes]

  [notes.audit-log]
    title = "Audit log"
    description = """\
It is now possible to get the audit log from the Omni. By default it's disabled. To enable, pass
`--audit-log-dir <dir>` to the Omni. The audit log will be written to the specified directory, separated by day.

Retention is set to 30 days (including the current day). The audit log is written in JSON format, where each entry is
a JSON object.

There are two ways to get audit log, and for both you need Admin role:
1. By using the UI: Simply click "Download audit log" in the main menu.
2. Using `omnictl audit-log` command. This command will stream the audit log from the Omni to the local machine stdout.
"""

  [notes.allow-multiple-ip]
    title = "Allow multiple IP's in `siderolink-wireguard-advertised-addr` flag"
    description = """\
The `siderolink-wireguard-advertised-addr` flag now accepts multiple IP addresses separated by commas. This is useful
when you have multiple IPs (IPv4 and IPv6) on the host machine and want to allow Talos nodes to connect to the Omni
using any of them.
"""

  [notes.tls-certs-reload]
    title = "TLS Cert Reload"
    description = """\
Omni service can now reload the TLS certs without restart.
"""

  [notes.cluster-sort]
    title = "Cluster Sort"
    description = """\
Cluster list on Clusters page can now be sorted by name or creation date.
Before it was always sorted by creation date (newest first).
"""
